site_name: Dynax Documentation
site_description: The documentation for the Dynax Python library.
copyright: Copyright &copy; 2025 Fabain Roth
repo_url: https://github.com/Drenderer/dynax
repo_name: Drenderer/dynax
strict: true # Do not allow warnings during the build process

theme:
  name: material
  logo: assetss/logo_minimal.png
  favicon: assetss/logo_minimal.png
  language: en
  features:
    - header.autohide
    - navigation.footer
    - search.suggest
    - search.highlight
    - toc.integrate # Table of contents is integrated on the left
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: spacy 
            force_inspection: true  # Required by hippogriffe
            show_symbol_type_heading: true  # show symbols for classes, functions, etc.
            show_symbol_type_toc: true
            show_root_heading: true 
            show_bases: false # Show base classes in the class documentation (This is done by hippogriffe so disable it here)
            show_source: false # Show source code links in the class documentation (Hippogiffe links to github so disable it here)
            heading_level: 3  #The initial heading level to use. (Size of the headings)
  - hippogriffe:
      show_bases: true
      show_source_links: all
      extra_public_objects:
        - diffrax.AbstractAdjoint
        - diffrax.RecursiveCheckpointAdjoint
        - diffrax.AbstractSolver
        - diffrax.AbstractStepSizeController
        - diffrax.Tsit5
        - diffrax.PIDController
        - diffrax.Solution
        - jax.nn.initializers.Initializer
        - numpy.dtype
        - jax._src.typing.SupportsDType
        - klax._wrappers.Constraint
        - klax._wrappers.Unwrappable

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Dynax: index.md
  - API:
    - api/datahandling.md
    - api/derivative_models.md
    - api/integration_models.md
    - api/latentspace.md
    - api/potentials.md
    - api/normalization.md
    - api/signals.md